### ISSUE TITLE
Help [Configure]: Change the size of Reboot and other buttons

### ISSUE THREAD

**Issue by AsarNaufil** [catppuccin/sddm#19]
Hi, I have looked into the files.. I am a novice.

How do I set this in a proper way so that all buttons are scaled up in size by a bit..
![image](https://github.com/catppuccin/sddm/assets/145439464/a3f265f7-5176-47d9-ab3a-9a27edd6cfb0)
![image](https://github.com/catppuccin/sddm/assets/145439464/1794fa76-96db-4941-ab74-c203152c1a3e)
Also, the buttons dont work for me.. so opening a separate issue for it..
Thanks for your time.

**Comment by isabelroses** [comment]
In order to change all buttons sizes you can:
- alter individual buttons https://github.com/catppuccin/sddm/blob/main/src/catppuccin-mocha/Components/SleepButton.qml#L9-L10 by changing the values they hold.
- or alter the entire screen size, https://github.com/catppuccin/sddm/blob/main/src/catppuccin-mocha/Components/LoginPanel.qml#L9-L10, which would stay fit to your screen but scale the buttons up in size.

**Comment by AsarNaufil** [comment]
Got it.. tysm!
